import type {
  ActivityEntry,
  AppData,
  ContentItem,
  ContentTypeDef,
  MediaItem,
  PageBlock,
  SiteSettings,
  UserAccount,
} from './types'
import { createBlock } from './blocks'

function block(type: PageBlock['type'], data: Record<string, string>): PageBlock {
  const b = createBlock(type)
  return { ...b, data: { ...b.data, ...data } }
}

function daysAgo(n: number, hour = 9): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(hour, 0, 0, 0)
  return d.toISOString()
}

function daysFromNow(n: number, hour = 9): string {
  return daysAgo(-n, hour)
}

export const users: UserAccount[] = [
  {
    id: 'user_jenny',
    name: 'Jenny Dang',
    email: 'jennyydang@gmail.com',
    role: 'Admin',
    status: 'active',
    avatarColor: 'from-brand-500 to-indigo-600',
    lastActive: daysAgo(0, 8),
    createdAt: daysAgo(210),
  },
  {
    id: 'user_marcus',
    name: 'Marcus Chen',
    email: 'marcus.chen@atlascms.dev',
    role: 'Editor',
    status: 'active',
    avatarColor: 'from-emerald-500 to-teal-600',
    lastActive: daysAgo(0, 11),
    createdAt: daysAgo(180),
  },
  {
    id: 'user_priya',
    name: 'Priya Patel',
    email: 'priya.patel@atlascms.dev',
    role: 'Author',
    status: 'active',
    avatarColor: 'from-amber-500 to-orange-600',
    lastActive: daysAgo(1, 16),
    createdAt: daysAgo(150),
  },
  {
    id: 'user_sam',
    name: 'Sam Rivera',
    email: 'sam.rivera@atlascms.dev',
    role: 'Contributor',
    status: 'active',
    avatarColor: 'from-rose-500 to-pink-600',
    lastActive: daysAgo(3, 14),
    createdAt: daysAgo(90),
  },
  {
    id: 'user_alex',
    name: 'Alex Kim',
    email: 'alex.kim@atlascms.dev',
    role: 'Author',
    status: 'invited',
    avatarColor: 'from-sky-500 to-blue-600',
    lastActive: daysAgo(9, 10),
    createdAt: daysAgo(6),
  },
]

export const contentTypes: ContentTypeDef[] = [
  {
    id: 'type_post',
    name: 'Blog Post',
    pluralName: 'Blog Posts',
    slug: 'posts',
    description: 'Long-form articles that appear in the blog and RSS feed.',
    icon: 'FileText',
    createdAt: daysAgo(200),
    fields: [
      { id: 'f_title', key: 'title', label: 'Title', type: 'text', required: true },
      { id: 'f_slug', key: 'slug', label: 'Slug', type: 'text', required: true, helpText: 'Used in the URL, e.g. /blog/your-slug' },
      { id: 'f_excerpt', key: 'excerpt', label: 'Excerpt', type: 'text', required: false, helpText: 'Short summary shown in listings and social previews.' },
      { id: 'f_body', key: 'body', label: 'Body', type: 'richtext', required: true },
      { id: 'f_image', key: 'featuredImage', label: 'Featured image', type: 'media', required: false },
      {
        id: 'f_category',
        key: 'category',
        label: 'Category',
        type: 'select',
        required: false,
        options: [
          { label: 'Product', value: 'product' },
          { label: 'Engineering', value: 'engineering' },
          { label: 'Company', value: 'company' },
          { label: 'Guides', value: 'guides' },
        ],
      },
      { id: 'f_tags', key: 'tags', label: 'Tags', type: 'text', required: false },
    ],
  },
  {
    id: 'type_page',
    name: 'Page',
    pluralName: 'Pages',
    slug: 'pages',
    description: 'Static site pages such as About, Pricing, or Contact.',
    icon: 'File',
    createdAt: daysAgo(200),
    fields: [
      { id: 'f_title', key: 'title', label: 'Title', type: 'text', required: true },
      { id: 'f_slug', key: 'slug', label: 'Slug', type: 'text', required: true },
      { id: 'f_body', key: 'body', label: 'Body', type: 'richtext', required: true },
      { id: 'f_image', key: 'featuredImage', label: 'Hero image', type: 'media', required: false },
      { id: 'f_nav', key: 'showInNav', label: 'Show in navigation', type: 'boolean', required: false },
    ],
  },
  {
    id: 'type_product',
    name: 'Product',
    pluralName: 'Products',
    slug: 'products',
    description: 'Catalog items for the marketing site product grid.',
    icon: 'Package',
    createdAt: daysAgo(120),
    fields: [
      { id: 'f_title', key: 'title', label: 'Name', type: 'text', required: true },
      { id: 'f_slug', key: 'slug', label: 'Slug', type: 'text', required: true },
      { id: 'f_excerpt', key: 'excerpt', label: 'Tagline', type: 'text', required: false },
      { id: 'f_body', key: 'body', label: 'Description', type: 'richtext', required: true },
      { id: 'f_image', key: 'featuredImage', label: 'Product image', type: 'media', required: false },
      { id: 'f_price', key: 'price', label: 'Price (USD)', type: 'number', required: true },
      { id: 'f_sku', key: 'sku', label: 'SKU', type: 'text', required: true },
      { id: 'f_featured', key: 'featured', label: 'Featured on homepage', type: 'boolean', required: false },
    ],
  },
]

const LOREM =
  'Atlas CMS gives your team a single source of truth for content. Draft, review, and publish from one place, with role-based permissions that keep everyone working confidently. This prototype demonstrates the core building blocks: schema-driven content types, a distraction-free editor, a searchable media library, and clear publishing states.'

export const media: MediaItem[] = [
  { id: 'media_1', filename: 'hero-dashboard.png', kind: 'image', mime: 'image/png', sizeKb: 842, width: 1920, height: 1080, alt: 'Product dashboard hero screenshot', uploadedById: 'user_marcus', uploadedAt: daysAgo(40), colorFrom: '#5570ff', colorTo: '#3038d6' },
  { id: 'media_2', filename: 'team-offsite-2026.jpg', kind: 'image', mime: 'image/jpeg', sizeKb: 1240, width: 2400, height: 1600, alt: 'Team offsite group photo', uploadedById: 'user_priya', uploadedAt: daysAgo(35), colorFrom: '#f59e0b', colorTo: '#ea580c' },
  { id: 'media_3', filename: 'brand-guidelines.pdf', kind: 'document', mime: 'application/pdf', sizeKb: 3210, alt: 'Brand guidelines document', uploadedById: 'user_jenny', uploadedAt: daysAgo(60), colorFrom: '#64748b', colorTo: '#334155' },
  { id: 'media_4', filename: 'product-tour.mp4', kind: 'video', mime: 'video/mp4', sizeKb: 48200, width: 1920, height: 1080, alt: 'Product tour walkthrough video', uploadedById: 'user_marcus', uploadedAt: daysAgo(20), colorFrom: '#ec4899', colorTo: '#be185d' },
  { id: 'media_5', filename: 'office-workspace.jpg', kind: 'image', mime: 'image/jpeg', sizeKb: 980, width: 2000, height: 1333, alt: 'Modern office workspace', uploadedById: 'user_sam', uploadedAt: daysAgo(18), colorFrom: '#10b981', colorTo: '#0d9488' },
  { id: 'media_6', filename: 'api-architecture.png', kind: 'image', mime: 'image/png', sizeKb: 560, width: 1600, height: 900, alt: 'API architecture diagram', uploadedById: 'user_marcus', uploadedAt: daysAgo(15), colorFrom: '#6366f1', colorTo: '#4338ca' },
  { id: 'media_7', filename: 'press-kit.zip', kind: 'document', mime: 'application/zip', sizeKb: 15400, alt: 'Press kit archive', uploadedById: 'user_jenny', uploadedAt: daysAgo(55), colorFrom: '#78716c', colorTo: '#44403c' },
  { id: 'media_8', filename: 'customer-quote-banner.png', kind: 'image', mime: 'image/png', sizeKb: 410, width: 1400, height: 700, alt: 'Customer testimonial banner', uploadedById: 'user_priya', uploadedAt: daysAgo(10), colorFrom: '#f43f5e', colorTo: '#e11d48' },
  { id: 'media_9', filename: 'onboarding-walkthrough.mp4', kind: 'video', mime: 'video/mp4', sizeKb: 62300, width: 1920, height: 1080, alt: 'Onboarding walkthrough video', uploadedById: 'user_sam', uploadedAt: daysAgo(8), colorFrom: '#0ea5e9', colorTo: '#0369a1' },
  { id: 'media_10', filename: 'pricing-table.png', kind: 'image', mime: 'image/png', sizeKb: 320, width: 1600, height: 1000, alt: 'Pricing comparison table', uploadedById: 'user_marcus', uploadedAt: daysAgo(6), colorFrom: '#8b5cf6', colorTo: '#6d28d9' },
  { id: 'media_11', filename: 'security-whitepaper.pdf', kind: 'document', mime: 'application/pdf', sizeKb: 2890, alt: 'Security whitepaper', uploadedById: 'user_jenny', uploadedAt: daysAgo(4), colorFrom: '#64748b', colorTo: '#1e293b' },
  { id: 'media_12', filename: 'summer-campaign-cover.jpg', kind: 'image', mime: 'image/jpeg', sizeKb: 1100, width: 2200, height: 1237, alt: 'Summer campaign cover art', uploadedById: 'user_priya', uploadedAt: daysAgo(2), colorFrom: '#facc15', colorTo: '#ca8a04' },
]

export const content: ContentItem[] = [
  {
    id: 'post_1',
    contentTypeId: 'type_post',
    title: 'Introducing Atlas CMS: content management, rebuilt',
    slug: 'introducing-atlas-cms',
    status: 'published',
    authorId: 'user_jenny',
    excerpt: 'Why we built a CMS around clarity, speed, and accessibility from day one.',
    body: LOREM,
    featuredImageId: 'media_1',
    tags: ['launch', 'product'],
    seoTitle: 'Introducing Atlas CMS',
    seoDescription: 'A content management system built for clarity, speed, and accessibility.',
    createdAt: daysAgo(42),
    updatedAt: daysAgo(40),
    publishedAt: daysAgo(40),
  },
  {
    id: 'post_2',
    contentTypeId: 'type_post',
    title: 'How we designed the editor for focus, not friction',
    slug: 'designing-the-editor',
    status: 'published',
    authorId: 'user_marcus',
    excerpt: 'A look at the UX decisions behind the writing experience.',
    body: LOREM,
    featuredImageId: 'media_6',
    tags: ['design', 'engineering'],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(28),
    publishedAt: daysAgo(28),
  },
  {
    id: 'post_3',
    contentTypeId: 'type_post',
    title: 'Role-based permissions, explained',
    slug: 'role-based-permissions-explained',
    status: 'published',
    authorId: 'user_priya',
    excerpt: 'What Admins, Editors, Authors, and Contributors can each do.',
    body: LOREM,
    tags: ['permissions', 'guides'],
    createdAt: daysAgo(22),
    updatedAt: daysAgo(20),
    publishedAt: daysAgo(20),
  },
  {
    id: 'post_4',
    contentTypeId: 'type_post',
    title: 'A practical guide to content modeling',
    slug: 'guide-to-content-modeling',
    status: 'in-review',
    authorId: 'user_priya',
    excerpt: 'Structure content once, reuse it everywhere.',
    body: LOREM,
    tags: ['guides'],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(1),
  },
  {
    id: 'post_5',
    contentTypeId: 'type_post',
    title: 'Q3 product roadmap preview',
    slug: 'q3-product-roadmap-preview',
    status: 'scheduled',
    authorId: 'user_jenny',
    excerpt: 'What is shipping next quarter across the platform.',
    body: LOREM,
    tags: ['product', 'company'],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    scheduledFor: daysFromNow(4, 8),
  },
  {
    id: 'post_6',
    contentTypeId: 'type_post',
    title: 'Draft: migrating from legacy CMS platforms',
    slug: 'migrating-from-legacy-cms',
    status: 'draft',
    authorId: 'user_sam',
    excerpt: 'A checklist for teams moving off older systems.',
    body: '',
    tags: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0, 10),
  },
  {
    id: 'post_7',
    contentTypeId: 'type_post',
    title: '2025 year in review',
    slug: '2025-year-in-review',
    status: 'archived',
    authorId: 'user_marcus',
    excerpt: 'Looking back at a year of milestones.',
    body: LOREM,
    tags: ['company'],
    createdAt: daysAgo(220),
    updatedAt: daysAgo(210),
    publishedAt: daysAgo(210),
  },
  {
    id: 'post_8',
    contentTypeId: 'type_post',
    title: 'Building an accessible design system',
    slug: 'building-an-accessible-design-system',
    status: 'draft',
    authorId: 'user_alex',
    excerpt: 'Notes from the design and engineering handoff.',
    body: '',
    tags: ['design'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0, 15),
  },
  {
    id: 'page_1',
    contentTypeId: 'type_page',
    title: 'About us',
    slug: 'about',
    status: 'published',
    authorId: 'user_jenny',
    excerpt: 'Our mission and the team behind Atlas.',
    body: LOREM,
    featuredImageId: 'media_2',
    tags: [],
    createdAt: daysAgo(180),
    updatedAt: daysAgo(60),
    publishedAt: daysAgo(180),
    blocks: [
      block('hero', {
        heading: 'We build tools for people who publish',
        subheading: 'Atlas started as a side project between two editors tired of fighting their CMS.',
        align: 'center',
        ctaLabel: 'Meet the team',
        ctaUrl: '#team',
      }),
      block('columns', {
        leftHeading: 'Our mission',
        leftBody: 'Give every team a content workflow that feels as good as the writing itself.',
        rightHeading: 'Our approach',
        rightBody: 'Ship small, listen closely, and keep the editor out of the way of the writer.',
      }),
      block('quote', {
        quote: 'The best CMS is the one your team forgets is even there.',
        attribution: 'Jenny Dang, Founder',
      }),
      block('spacer', { size: 'md' }),
      block('cta', {
        heading: 'Come work with us',
        body: 'We are a small, remote-first team building the next version of Atlas.',
        buttonLabel: 'View open roles',
        buttonUrl: '#careers',
      }),
    ],
  },
  {
    id: 'page_2',
    contentTypeId: 'type_page',
    title: 'Pricing',
    slug: 'pricing',
    status: 'published',
    authorId: 'user_marcus',
    excerpt: 'Plans for teams of every size.',
    body: LOREM,
    featuredImageId: 'media_10',
    tags: [],
    createdAt: daysAgo(170),
    updatedAt: daysAgo(6),
    publishedAt: daysAgo(170),
  },
  {
    id: 'page_3',
    contentTypeId: 'type_page',
    title: 'Contact',
    slug: 'contact',
    status: 'published',
    authorId: 'user_jenny',
    excerpt: 'Get in touch with our team.',
    body: LOREM,
    tags: [],
    createdAt: daysAgo(175),
    updatedAt: daysAgo(90),
    publishedAt: daysAgo(175),
  },
  {
    id: 'page_4',
    contentTypeId: 'type_page',
    title: 'Security & compliance',
    slug: 'security',
    status: 'in-review',
    authorId: 'user_marcus',
    excerpt: 'How we keep customer data safe.',
    body: LOREM,
    featuredImageId: 'media_11',
    tags: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
  },
  {
    id: 'product_1',
    contentTypeId: 'type_product',
    title: 'Atlas CMS — Team plan',
    slug: 'team-plan',
    status: 'published',
    authorId: 'user_jenny',
    excerpt: 'For growing teams that publish every week.',
    body: LOREM,
    featuredImageId: 'media_10',
    tags: [],
    createdAt: daysAgo(100),
    updatedAt: daysAgo(6),
    publishedAt: daysAgo(100),
  },
  {
    id: 'product_2',
    contentTypeId: 'type_product',
    title: 'Atlas CMS — Enterprise plan',
    slug: 'enterprise-plan',
    status: 'draft',
    authorId: 'user_priya',
    excerpt: 'Advanced controls for larger organizations.',
    body: '',
    tags: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0, 12),
  },
]

export const activity: ActivityEntry[] = [
  { id: 'act_1', kind: 'published', message: 'published "Introducing Atlas CMS: content management, rebuilt"', actorId: 'user_jenny', targetId: 'post_1', timestamp: daysAgo(40) },
  { id: 'act_2', kind: 'published', message: 'published "How we designed the editor for focus, not friction"', actorId: 'user_marcus', targetId: 'post_2', timestamp: daysAgo(28) },
  { id: 'act_3', kind: 'published', message: 'published "Role-based permissions, explained"', actorId: 'user_priya', targetId: 'post_3', timestamp: daysAgo(20) },
  { id: 'act_4', kind: 'uploaded', message: 'uploaded onboarding-walkthrough.mp4', actorId: 'user_sam', targetId: 'media_9', timestamp: daysAgo(8) },
  { id: 'act_5', kind: 'updated', message: 'updated "Security & compliance"', actorId: 'user_marcus', targetId: 'page_4', timestamp: daysAgo(2) },
  { id: 'act_6', kind: 'invited', message: 'invited Alex Kim as Author', actorId: 'user_jenny', targetId: 'user_alex', timestamp: daysAgo(6) },
  { id: 'act_7', kind: 'created', message: 'created draft "Atlas CMS — Enterprise plan"', actorId: 'user_priya', targetId: 'product_2', timestamp: daysAgo(2) },
  { id: 'act_8', kind: 'updated', message: 'updated "Q3 product roadmap preview" and scheduled it', actorId: 'user_jenny', targetId: 'post_5', timestamp: daysAgo(1) },
  { id: 'act_9', kind: 'created', message: 'created draft "Building an accessible design system"', actorId: 'user_alex', targetId: 'post_8', timestamp: daysAgo(1) },
  { id: 'act_10', kind: 'uploaded', message: 'uploaded summer-campaign-cover.jpg', actorId: 'user_priya', targetId: 'media_12', timestamp: daysAgo(2) },
  { id: 'act_11', kind: 'updated', message: 'moved "A practical guide to content modeling" to review', actorId: 'user_priya', targetId: 'post_4', timestamp: daysAgo(1) },
  { id: 'act_12', kind: 'created', message: 'created draft "Draft: migrating from legacy CMS platforms"', actorId: 'user_sam', targetId: 'post_6', timestamp: daysAgo(3) },
]

export const settings: SiteSettings = {
  siteName: 'Atlas CMS Demo',
  siteUrl: 'https://demo.atlascms.dev',
  tagline: 'Content management, rebuilt for clarity.',
  description:
    'Atlas CMS is a prototype content platform showing how schema-driven content types, publishing workflows, and role-based access can work together.',
  supportEmail: 'support@atlascms.dev',
  timezone: 'America/Los_Angeles',
  defaultLocale: 'en-US',
  postsPerPage: 10,
  maintenanceMode: false,
  allowComments: true,
  requireReviewBeforePublish: true,
}

export function buildSeedData(): AppData {
  return { contentTypes, content, media, users, activity, settings }
}
